### ISSUE TITLE
Bug in refcounter memory order

### ISSUE THREAD

**Issue by MBkkt** [disba1ancer/dse#5]
https://github.com/disba1ancer/dse/blob/master/src/util/future.h#L37 for this line need to acquire (bug)
https://github.com/disba1ancer/dse/blob/master/src/util/future.h#L48 relaxed enough in this line (enhancement)

Correct example, with some explanations:
https://www.boost.org/doc/libs/1_76_0/doc/html/atomic/usage_examples.html#boost_atomic.usage_examples.example_reference_counters

**Comment by MBkkt** [comment]
Why unconfirmed? @disba1ancer 
You can write tests and run them with thread sanitizer.  With any order weaker than acq_rel tsan will report the race.  Remember, though, that it can't work with atomic_thread_fence.

**Comment by disba1ancer** [comment]
> Why unconfirmed? @disba1ancer
> You can write tests and run them with thread sanitizer. With any order weaker than acq_rel tsan will report the race. Remember, though, that it can't work with atomic_thread_fence.

I deleted unconfirmed tag a long time ago. It is really bug. I fixed it locally, fix appears after next push. As for tests, I don't understand them.

**Comment by MBkkt** [comment]
I didn't notice, sorry
